# Generated by Django 3.0.2 on 2020-03-22 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bored', 'bored'), ('whine', 'whine'), ('whatever', 'whatever'), ('share positive energy', 'share positive energy')], max_length=100)),
                ('descn', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('num_posts', models.IntegerField(default=0)),
                ('num_replies', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Category')),
            ],
            options={
                'ordering': ('-created_on', 'updated_on'),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(max_length=200)),
                ('poster_ip', models.GenericIPAddressField()),
                ('subject', models.CharField(max_length=999)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('context', models.TextField(default='')),
                ('num_views', models.IntegerField(default=0)),
                ('num_replies', models.PositiveSmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('last_reply_on', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='uploads/attachments')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.Category')),
                ('forum', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.Forum')),
                ('posted_by_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_reply_on',),
                'get_latest_by': 'created_on',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(max_length=999)),
                ('poster_ip', models.GenericIPAddressField()),
                ('message', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='uploads/attachments')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Post')),
                ('posted_by_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_on',),
            },
        ),
    ]
